// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	models "github.com/natanaelrusli/parking-lot/models"
	mock "github.com/stretchr/testify/mock"
)

// ParkingLotObserver is an autogenerated mock type for the ParkingLotObserver type
type ParkingLotObserver struct {
	mock.Mock
}

// OnParkingLotStatusChanged provides a mock function with given fields: status
func (_m *ParkingLotObserver) OnParkingLotStatusChanged(status models.ParkingLotStatus) {
	_m.Called(status)
}

// NewParkingLotObserver creates a new instance of ParkingLotObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParkingLotObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParkingLotObserver {
	mock := &ParkingLotObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
